### ISSUE TITLE
Dropwizard script needs updating

### ISSUE THREAD

**Issue by joakime** [jetty-project/external-oss-builds#2]
The script for dropwizard is using `master` as the default branch to build from.

The current default branch at dropwizard is `release/2.1.x`

Unfortunately, the staging group repo is not listed in that pom on that branch.

**Comment by joakime** [comment]
@olamy I updated the default branch in commit 65662659bfdae8a31c2141ab4d18b688be3a8ab5

**Comment by joakime** [comment]
There's a pgpverify step that needs tending to as well.

```
[ERROR] Failed to execute goal org.simplify4u.plugins:pgpverify-maven-plugin:1.16.0:check (default) on project dropwizard-parent: Execution default of goal org.simplify4u.plugins:pgpverify-maven-plugin:1.16.0:check failed: Unable to load the mojo 'check' (or one of its required components) from the plugin 'org.simplify4u.plugins:pgpverify-maven-plugin:1.16.0': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR] 
[ERROR] 1) Error injecting constructor, java.lang.NullPointerException
[ERROR]   at org.simplify4u.plugins.ArtifactResolver.<init>(Unknown Source)
[ERROR]   while locating org.simplify4u.plugins.ArtifactResolver
[ERROR]     for field at org.simplify4u.plugins.AbstractPGPMojo.artifactResolver(Unknown Source)
[ERROR]   while locating org.simplify4u.plugins.CheckMojo
[ERROR]   at ClassRealm[plugin>org.simplify4u.plugins:pgpverify-maven-plugin:1.16.0, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR]   while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value="org.simplify4u.plugins:pgpverify-maven-plugin:1.16.0:check")
[ERROR] 
[ERROR] 1 error
[ERROR]       role: org.apache.maven.plugin.Mojo
[ERROR]   roleHint: org.simplify4u.plugins:pgpverify-maven-plugin:1.16.0:check
```

**Comment by joakime** [comment]
We should probably split the dropwizard script in 2 as well.

1. For Jetty 9.4.x series use dropwizard branch `release/2.1.x`
2. For Jetty 11.0.x series use dropwizard branch `release/4.0.x`

**Comment by joakime** [comment]
The `release/4.0.x` branch works, but we need to update the staging repo in 2 poms.

``` diff
[release/4.0.x*]$ git diff
diff --git a/docs/source/examples/pom.xml b/docs/source/examples/pom.xml
index 873e0ccef..0810abf26 100644
--- a/docs/source/examples/pom.xml
+++ b/docs/source/examples/pom.xml
@@ -64,4 +64,17 @@
             </plugins>
         </pluginManagement>
     </build>
+    <repositories>
+        <repository>
+            <id>oss-jetty</id>
+            <name>Sonatype Jetty Staging</name>
+            <url>https://oss.sonatype.org/content/groups/jetty-with-staging</url>
+            <releases>
+                <enabled>true</enabled>
+            </releases>
+            <snapshots>
+                <enabled>false</enabled>
+            </snapshots>
+        </repository>
+    </repositories>
 </project>
diff --git a/pom.xml b/pom.xml
index 8a731fedb..e95b66ce0 100644
--- a/pom.xml
+++ b/pom.xml
@@ -238,6 +238,17 @@
     </mailingLists>
 
     <repositories>
+        <repository>
+            <id>oss-jetty</id>
+            <name>Sonatype Jetty Staging</name>
+            <url>https://oss.sonatype.org/content/groups/jetty-with-staging</url>
+            <releases>
+                <enabled>true</enabled>
+            </releases>
+            <snapshots>
+                <enabled>false</enabled>
+            </snapshots>
+        </repository>
         <repository>
             <id>ossrh</id>
             <name>Sonatype Nexus Snapshots</name>
```

**Comment by olamy** [comment]
should be fixed by using our nexus. (see https://github.com/jetty-project/external-oss-builds/commit/c785c0c6b08167330270c1fb63876e7884e729ab )
But the problem might be to include repos used by dropwizard build in their build.
perso I don't like the idea about external projects using `https://oss.sonatype.org/content/groups/jetty-with-staging` in their pom.
especially because we can stage/restage version with same version number but different content.

**Comment by joakime** [comment]
Being CI builds, those staged versions are not cached. (or they shouldn't be cached by something like nexus).
So that's not an issue in my mind.

The current solutions with a `local.central` at `file://root/.m2/` is super fragile.
We need a better solution.

**Comment by olamy** [comment]
> Being CI builds, those staged versions are not cached. (or they shouldn't be cached by something like nexus). So that's not an issue in my mind.

for us not an issue for sure but not having it in dropwizard source code as the proposed diff above (every single repomanager is caching per default release version number so it's not a common usage to not caching release version number)


> 
> The current solutions with a `local.central` at `file://root/.m2/` is super fragile. We need a better solution.

yup but it's default usage from m-invoker-p. but normally the plugin with a correct configuration should pick/merge settings
coming from https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-archetypes/src/test/resources/settings.xml

**Comment by olamy** [comment]
got clean build (of both 2.1.x and 4.0.x)

4.0.x: https://jenkins.webtide.net/job/external_oss/job/dropwizard-build/47/
the only remaining issue is due to the fact we start our k8s temporary pods as root.

**Comment by olamy** [comment]
resolved

**Comment by joakime** [comment]
Nope, not done yet.

**Comment by joakime** [comment]
We need the split between `release/2.1.x` (Jetty-9.4.x) and `release/4.0.x` (Jetty 11.0.x).
Those have different setup and requirements, so need different scripts.

**Comment by olamy** [comment]
actually it's only a matter of correct parameters.
<img width="1405" alt="dropwizard-2 1 x" src="https://user-images.githubusercontent.com/19728/174904515-af929687-ce1a-45a7-bc7c-7b713f615588.png">
<img width="1479" alt="dropwizard-4 0 x" src="https://user-images.githubusercontent.com/19728/174904533-487ab9ed-5047-4fe6-992e-d99f6dbc8ebd.png">

**Comment by olamy** [comment]
not sure what you want exactly?

**Comment by joakime** [comment]
The release/4.0.x doesn't build this way, as once it hits the examples projects it doesn't pick up the staged jetty versions.

**Comment by joakime** [comment]
In `release/4.0.x` branch has an isolate pom in the docs/examples that isn't tied back to the top level pom.
So while the base code will work, the examples wont.

This is not a problem in `release/2.1.x` branch, as it doens't have the same pom structure.

**Comment by olamy** [comment]
the solution was to inject repositories via a settings.xml which use our CI repository manager instance and so if needed the staged versions (depending on the parameters of the build)
it works for other builds.
`docs/examples` is using the dropwizard-dependencies bom which is part of the reactor build 

https://github.com/dropwizard/dropwizard/blob/c8de4356e6fabdfe99408fe79054d9e58525ca58/docs/source/examples/pom.xml#L36

and docs/example is part of the main build :
https://github.com/dropwizard/dropwizard/blob/c8de4356e6fabdfe99408fe79054d9e58525ca58/pom.xml#L53

the only very minor issue which we probably do not have any concerns is the build of the dropwizard-archetypes/java-simple which eventually will not use the correct version. But it's not anything runtime concerning Jetty.
